decades = [1880, 1890, 1900, 1910, 1920, 1930, 1940, 1950, 1960, 1970, 1980, 1990, 2000, 2010]

diseases = ["Active tuberculosis",
            "Acute hepatitis C",
            "Acute nonparalytic poliomyelitis",
            "Acute paralytic poliomyelitis",
            "Acute poliomyelitis",
            "Acute type A viral hepatitis",
            "Acute type B viral hepatitis",
            "Amebic dysentery",
            "Anthrax",
            "Aseptic meningitis",
            "Babesiosis",
            "Bacillary dysentery",
            "Brucellosis",
            "Campylobacteriosis",
            "Chlamydia trachomatis infection",
            "Chlamydial infection",
            "Cholera",
            "Coccidioidomycosis",
            "Cryptosporidiosis",
            "Dengue",
            "Dengue hemorrhagic fever",
            "Dengue without warning signs",
            "Diphtheria",
            "Disorder of nervous system caused by West Nile virus",
            "Dysentery",
            "Encephalitis",
            "Encephalitis lethargica",
            "Giardiasis",
            "Gonorrhea",
            "Haemophilus influenzae infection",
            "Hepatitis non-A non-B",
            "Human anaplasmosis caused by Anaplasma phagocytophilum",
            "Human ehrlichiosis caused by Ehrlichia chaffeensis",
            "Infantile paralysis",
            "Infection caused by Escherichia coli",
            "Infection caused by larvae of Trichinella",
            "Infection caused by non-cholerae vibrio",
            "Infection caused by Shiga toxin producing Escherichia coli",
            "Infective encephalitis",
            "Inflammatory disease of liver",
            "Influenza",
            "Invasive drug resistant Streptococcus pneumoniae disease",
            "Invasive Group A beta-hemolytic streptococcal disease",
            "Invasive meningococcal disease",
            "Invasive Streptococcus pneumoniae disease",
            "Legionella infection",
            "Leprosy",
            "Lobar pneumonia",
            "Lyme disease",
            "Malaria",
            "Measles",
            "Meningitis",
            "Meningococcal infectious disease",
            "Meningococcal meningitis",
            "Mumps",
            "Murine typhus",
            "Ornithosis",
            "Pellagra",
            "Pertussis",
            "Pneumonia",
            "Post-infectious encephalitis",
            "Primary encephalitis",
            "Rocky Mountain spotted fever",
            "Rubella",
            "Salmonella infection",
            "Scarlet fever",
            "Shigellosis",
            "Smallpox",
            "Smallpox without rash",
            "Spotted fever group rickettsial disease",
            "Streptococcal sore throat",
            "Tetanus",
            "Toxic shock syndrome",
            "Tuberculosis",
            "Tularemia",
            "Typhoid and paratyphoid fevers",
            "Typhoid fever",
            "Typhus group rickettsial disease",
            "Varicella",
            "Viral hepatitis",
            "Viral hepatitis type B",
            "Viral hepatitis, type A",
            "West Nile fever without encephalitis",
            "Yellow fever"]

states = ["WISCONSIN",
          "OHIO",
          "MICHIGAN",
          "NEVADA",
          "NEW JERSEY",
          "WASHINGTON",
          "DELAWARE",
          "KENTUCKY",
          "WYOMING",
          "INDIANA",
          "NEW HAMPSHIRE",
          "ILLINOIS",
          "MISSISSIPPI",
          "NEW YORK",
          "NEBRASKA",
          "MAINE",
          "ARIZONA",
          "MINNESOTA",
          "ARKANSAS",
          "NORTH DAKOTA",
          "DISTRICT OF COLUMBIA",
          "MARYLAND",
          "VERMONT",
          "NEW MEXICO",
          "SOUTH CAROLINA",
          "MASSACHUSETTS",
          "IOWA",
          "RHODE ISLAND",
          "CONNECTICUT",
          "GEORGIA",
          "COLORADO",
          "SOUTH DAKOTA",
          "TENNESSEE",
          "KANSAS",
          "VIRGINIA",
          "ALABAMA",
          "OKLAHOMA",
          "FLORIDA",
          "TEXAS",
          "MONTANA",
          "UTAH",
          "MISSOURI",
          "CALIFORNIA",
          "IDAHO",
          "NORTH CAROLINA",
          "WEST VIRGINIA",
          "OREGON",
          "LOUISIANA",
          "PENNSYLVANIA",
          "PUERTO RICO",
          "ALASKA",
          "HAWAII",
          "GUAM",
          "VIRGIN ISLANDS, U.S.",
          "AMERICAN SAMOA",
          "NORTHERN MARIANA ISLANDS"]
